name: 'ci'

on:
  pull_request:
  push:
    branches:
      - main
      - debug

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build
  #       run: npm run build

  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci
          sudo apt update && sudo apt install zstd
          sudo cp /usr/bin/zstd /usr/local/bin/zstd

      - name: Run tests
        uses: ./
        with:
          bucket: fake-bucket-name
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build
  #       run: npm run lint
